<?php

namespace Tekstove\TekstoveBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * LyricRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LyricRepository extends EntityRepository
{
    public function filterPublicAvailable(\Doctrine\ORM\QueryBuilder $qb)
    {
        return $qb;
    }
}
