index:
    path:     /
    defaults: { _controller: SiteBundle:Index:index }
contactsFriends:
    path: /contacts/partners
    defaults: { _controller: SiteBundle:Contacts:partners }
contacts:
    path: /contacts
    defaults: { _controller: SiteBundle:Contacts:contacts }

login:
    path: /login
    defaults: { _controller: SiteBundle:User:login }
loginCheck:
    path: /loginCheck
logout:
    path: /logout

register:
    path: /user/register
    defaults: { _controller: SiteBundle:User:register }
    methods: [GET, POST]

userView:
    path: /user/view/{id}
    defaults: { _controller: SiteBundle:User:view }
    
lyricView:
    path: /lyric/view/{id}
    defaults: { _controller: SiteBundle:Lyric:view }
    requirements:
        id:  \d+

lyricAdd:
    path: /lyric/add
    defaults: { _controller: SiteBundle:Lyric:add }
    methods: [GET, POST]

lyricEdit:
    path: /lyric/edit/{id}
    defaults: { _controller: SiteBundle:Lyric:edit }
    requirements:
        id: \d+

artistBrowse:
    path: /artist/browse/{id}
    defaults: { _controller: SiteBundle:Artist:browse }
    requirements:
        id: \d+
    
artistList:
    path: /artist/list/{letter}
    defaults: { _controller: SiteBundle:Artist:list }
    
tekstove_site_album_view:
    path: /album/browse/{id}
    defaults: { _controller: SiteBundle:Album:view }
    requirements:
        id: \d+

chat:
    path: /chat
    defaults: { _controller: SiteBundle:Chat:index }
