index:
    path:     /
    defaults: { _controller: SiteBundle:Index:index }
    methods: [GET]

contactsFriends:
    path: /contacts/partners
    defaults: { _controller: SiteBundle:Contacts:partners }
    methods: [GET]

contacts:
    path: /contacts
    defaults: { _controller: SiteBundle:Contacts:contacts }
    methods: [GET]

login:
    path: /login
    defaults: { _controller: SiteBundle:User:login }
    methods: [GET, POST]
    schemes:  [https]

loginCheck:
    path: /loginCheck
    methods: [GET, POST]

logout:
    path: /logout
    methods: [GET, POST]

register:
    path: /user/register
    defaults: { _controller: SiteBundle:User:register }
    methods: [GET, POST]
    schemes:  [https]

tekstove_site.user.password_reset.request:
    path: /user/password-reset/request
    defaults: { _controller: SiteBundle:User:passwordResetRequest}
    methods: [GET, POST]
    schemes: [https]
    
tekstove_site.user.password_reset.confirm:
    path: /user/password-reset/confirm/{key}
    defaults: { _controller: SiteBundle:User:passwordResetConfirm}
    methods: [GET, POST]
    schemes: [https]

userView:
    path: /user/view/{id}
    defaults: { _controller: SiteBundle:User:view }
    methods: [GET]

tekstove.site.user.edit:
    path: /user/edit/{id}
    defaults: { _controller: SiteBundle:User:edit }
    methods: [GET, POST]

userPmList:
    path: /user/pm/list
    defaults: { _controller: SiteBundle:User\Pm:list }
    methods: [GET]
    
tekstove_site.user.pm.send:
    path: /user/message/{toUserId}/{title}
    defaults: { _controller: SiteBundle:User\Pm:add, title: '' }
    methods: [GET, POST]
    
tekstove.site.user.pm.view:
    path: /user/pm/view/{id}
    defaults: { _controller: SiteBundle:User\Pm:view }
    methods: [GET]
    
lyricView:
    path: /lyric/view/{id}
    defaults: { _controller: SiteBundle:Lyric:view }
    requirements:
        id:  \d+
    methods: [GET]

tekstove_api_lyric_top100:
    path: "/lyrics/top100/{sort}"
    defaults: { _controller: SiteBundle:Lyric:top }
    methods: [GET]
    
tekstove.site.popular.history:
    path: "/lyrics/popular/{year}/{month}"
    defaults: { _controller: SiteBundle:Lyric:popularHistory }
    methods: [GET]

lyricAdd:
    path: /lyric/add
    defaults: { _controller: SiteBundle:Lyric:add }
    methods: [GET, POST]

lyricEdit:
    path: /lyric/edit/{id}
    defaults: { _controller: SiteBundle:Lyric:edit }
    requirements:
        id: \d+
    methods: [GET, POST]
        
tekstove_site.lyric.search:
    path: /lyric/search
    defaults: { _controller: SiteBundle:Lyric:search }
    methods: [GET]

artistBrowse:
    path: /artist/browse/{id}
    defaults: { _controller: SiteBundle:Artist:browse }
    requirements:
        id: \d+
    methods: [GET]
    
artistList:
    path: /artist/list/{letter}
    defaults: { _controller: SiteBundle:Artist:list }
    methods: [GET]
    
tekstove_site_album_view:
    path: /album/view/{id}
    defaults: { _controller: SiteBundle:Album:view }
    requirements:
        id: \d+
    methods: [GET]
        
tekstove.site.forum.category.list:
    path: /forum/category/list
    defaults: { _controller: SiteBundle:Forum\Category:list }
    methods: [GET]

tekstove.site.forum.topic.list:
    path: /forum/category/{categoryId}/topics
    defaults: { _controller: SiteBundle:Forum\Topic:list }
    requirements:
        categoryId: \d+
    methods: [GET]
        
tekstove.site.forum.topic.view:
    path: /forum/topic/{id}
    defaults: { _controller: SiteBundle:Forum\Topic:view }
    requirements:
        id: \d+
    methods: [GET]
        
tekstove.site.forum.topic.new:
    path: /forum/category/{categoryId}/topic/add
    defaults: { _controller: SiteBundle:Forum\Topic:new }
    requirements:
        categoryId: \d+
    methods: [GET, POST]
        
tekstove.site.forum.post.new:
    path: /foum/topic/{topicId}/post
    defaults: { _controller: SiteBundle:Forum\Post:add }
    requirements:
        id: \d+
    methods: [GET, POST]
        
tekstove.site.forum.post.newest:
    path: /forum/post/newest
    defaults: { _controller: SiteBundle:Forum\Post:listNew }
    methods: [GET]

chat:
    path: /chat
    defaults: { _controller: SiteBundle:Chat:index }
    methods: [GET]

tekstove.feed.forum.topic:
    path: /feed/forum/topic.xml
    defaults: { _controller: SiteBundle:Feed\Forum:Topic, _format:xml }
    methods: [GET]
