security:
    encoders:
        Tekstove\SiteBundle\Model\User:
            class: Tekstove\SiteBundle\Model\User\Provider\User
            algorithm: md5
            encode_as_base64: false
            iterations: 1
    providers:
        api:
                id: tekstove.provider.user
    firewalls:
        secured_area:
            pattern:   ^/
            anonymous: ~
            form_login:
                login_path: login
                check_path: loginCheck
            logout:
                path:   logout
                target: /
