security:
    encoders:
        Tekstove\SiteBundle\Model\User:
            class: Tekstove\SiteBundle\Model\User\Provider\User
            algorithm: md5
            encode_as_base64: false
            iterations: 1
    providers:
        security.provider.tekstove.api:
                id: tekstove.provider.user
    firewalls:
        tekstove_firewall:
            pattern:   ^/
            stateless: false
            wsse: true
            anonymous: ~
            form_login:
                login_path: login
                check_path: loginCheck
                remember_me: true
            remember_me:
                secret: '%secret%'
                lifetime: 604800
                path: /
            logout:
                path:   logout
                target: /
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
