services:
    tekstoveCache.cache.memcached:
        class: Tekstove\CacheBundle\Model\Cache\Adapter\Memcached
        arguments:
            server1:
                - { host: 'localhost', port: 11211, weight: ~ }
    tekstoveCache.cache:
        class: Tekstove\CacheBundle\Model\Cache
        arguments: ["@tekstoveCache.cache.memcached"]
    
    tekstove.security.lyric_voter:
        class: Tekstove\SiteBundle\Security\Authorization\Voter\LyricVoter
        public: false
        tags:
            - { name: security.voter }
    
    tekstove.provider.user:
        class: Tekstove\SiteBundle\Model\User\Provider\ApiProvider
        arguments:
            gateway: "@tekstove.gateway.userProvider"
            
    tekstove.gateway.userProvider:
        class: Tekstove\SiteBundle\Model\User\Provider\ApiGateway
        factory: [Tekstove\SiteBundle\Model\Gateway\GatewayFactory, createUserProviderGateway]
        shared: false

    tekstove.gateway.user:
        class: Tekstove\SiteBundle\Model\Gateway\User\UserGateway
        factory: [Tekstove\SiteBundle\Model\Gateway\GatewayFactory, createUserGateway]
        shared: false

    tesktove.gateway.lyric:
        class: Tekstove\SiteBundle\Model\Gateway\Lyric\LyricGateway
        factory: [Tekstove\SiteBundle\Model\Gateway\GatewayFactory, createLyricGateway]
        arguments: ["@security.token_storage"]
        shared: false

    tekstove.gateway.lyric.credentials:
        class: Tekstove\SiteBundle\Model\Gateway\Lyric\LyricGateway
        factory: [Tekstove\SiteBundle\Model\Gateway\GatewayFactory, createLyricCredentialsGateway]
        arguments: ["@security.token_storage"]
        shared: false

    wsse.security.authentication.provider:
        class: Tekstove\SiteBundle\Security\Authentication\Provider\TekstoveApiWsseProvider
        arguments:
            - '@tekstove.provider.user'
        public: false

    security.authentication.failure_handler:
        class: Symfony\Component\Security\Http\Authentication\DefaultAuthenticationFailureHandler
        arguments:
            - "@http_kernel"
            - "@security.http_utils"
            
    security.authentication.success_handler:
        class: Symfony\Component\Security\Http\Authentication\DefaultAuthenticationSuccessHandler
        arguments:
            - "@security.http_utils"

    wsse.security.authentication.listener:
        class: Tekstove\SiteBundle\Security\Firewall\TekstoveApiWsseListener
        arguments:
          - '@security.token_storage'
          - '@security.authentication.manager'
          - '@security.authentication.session_strategy'
          - '@security.http_utils'
          - 'wsse'
          - '@security.authentication.success_handler'
          - '@security.authentication.failure_handler'
          - []
          - '@logger'
          - ~
        public: false
