services:
    tekstove.provider.user:
        class: Tekstove\SiteBundle\Model\User\Provider\ApiProvider
        arguments:
            gateway: "@tekstove.gateway.userProvider"
            
    tekstove.gateway.factory:
        class: Tekstove\SiteBundle\Model\Gateway\GatewayFactory
        arguments: ["%tekstove.api_url%", "@security.token_storage", "@request_stack"]
            
    tekstove.gateway.userProvider:
        class: Tekstove\SiteBundle\Model\User\Provider\ApiGateway
        factory: ["@tekstove.gateway.factory", createUserProviderGateway]
        shared: false

    tekstove.gateway.user:
        class: Tekstove\SiteBundle\Model\Gateway\User\UserGateway
        factory: ["@tekstove.gateway.factory", createUserGateway]
        shared: false
        
    tekstove.gateway.user.pm:
        class: Tekstove\SiteBundle\Model\Gateway\Tekstove\User\PmGateway
        factory: ["@tekstove.gateway.factory", createUserPmGateway]
        shared: false
        
    tekstove.gateway.user.register:
        class: Tekstove\SiteBundle\Model\Gateway\User\UserGateway
        factory: ["@tekstove.gateway.factory", createUserRegisterGateway]
        shared: false

    tesktove.gateway.lyric:
        class: Tekstove\SiteBundle\Model\Gateway\Lyric\LyricGateway
        factory: ["@tekstove.gateway.factory", createLyricGateway]
        shared: false
        
    tekstove.gateway.lyric.credentials:
        class: Tekstove\SiteBundle\Model\Gateway\Lyric\LyricGateway
        factory: ["@tekstove.gateway.factory", createLyricCredentialsGateway]
        arguments: ["@security.token_storage"]
        shared: false

    tekstove.gateway.artist:
        class: Tekstove\SiteBundle\Model\Gateway\Artist\ArtistGateway
        factory: ["@tekstove.gateway.factory", createArtistGateway]
        shared: false
        
    tekstove.gateway.album:
        class: Tekstove\SiteBundle\Model\Gateway\Album\AlbumGateway
        factory: ["@tekstove.gateway.factory", createAlbumGateway]
        shared: false
        
    tekstove.gateway.forum.category:
        class: Tekstove\SiteBundle\Model\Gateway\Forum\CategoryGateway
        factory: ["@tekstove.gateway.factory", createForumCategoryGateway]
        shared: false
        
    tekstove.gateway.forum.topic:
        class: Tekstove\SiteBundle\Model\Gateway\Forum\TopicGateway
        factory: ["@tekstove.gateway.factory", createForumTopicGateway]
        shared: false

    tekstove.gateway.forum.post:
        class: Tekstove\SiteBundle\Model\Gateway\Forum\PostGateway
        factory: ["@tekstove.gateway.factory", createForumPostGateway]
        shared: false
    
    tekstove.gateway.language:
        class: Tekstove\SiteBundle\Model\Gateway\Tekstove\Language\LanguageGateway
        factory: ["@tekstove.gateway.factory", createLanguageGateway]
        shared: false

    wsse.security.authentication.provider:
        class: Tekstove\SiteBundle\Security\Authentication\Provider\TekstoveApiWsseProvider
        arguments:
            - '@tekstove.provider.user'
        public: false

    security.authentication.failure_handler:
        class: Symfony\Component\Security\Http\Authentication\DefaultAuthenticationFailureHandler
        arguments:
            - "@http_kernel"
            - "@security.http_utils"
            
    security.authentication.success_handler:
        class: Symfony\Component\Security\Http\Authentication\DefaultAuthenticationSuccessHandler
        arguments:
            - "@security.http_utils"

    wsse.security.authentication.listener:
        class: Tekstove\SiteBundle\Security\Firewall\TekstoveApiWsseListener
        arguments:
          - '@security.token_storage'
          - '@security.authentication.manager'
          - '@security.authentication.session_strategy'
          - '@security.http_utils'
          - 'wsse'
          - '@security.authentication.success_handler'
          - '@security.authentication.failure_handler'
          - []
          - '@logger'
          - ~
        public: false

    tekstove.form.lyric:
        class: Tekstove\SiteBundle\Form\Type\LyricType
        arguments: ['@request_stack', '@tekstove.gateway.artist', '@tekstove.gateway.language']
        tags:
            - { name: form.type }

    tekstove.site.gateway_pagination:
        class: Tekstove\SiteBundle\Subscriber\TekstoveGatewayPaginationSubscriber
        arguments: ['@request_stack']
        tags:
            - { name: knp_paginator.subscriber }

    tekstove.site.twig.filter.loggedOnly:
        class: Tekstove\SiteBundle\Twig\Filter\LoggedOnlyLink
        arguments: ["@security.token_storage", "@router"]
        public: false
        tags:
            - { name: twig.extension }
    tekstove.site.twig.extension.text:
        class: Twig_Extensions_Extension_Text
        public: false
        tags:
            - { name: twig.extension }
