services:
    tekstove.provider.user:
        class: Tekstove\SiteBundle\Model\User\Provider\ApiProvider
        arguments: ["@tekstove.gateway.userProvider"]
        public: true
            
    tekstove.gateway.factory:
        class: Tekstove\SiteBundle\Model\Gateway\GatewayFactory
        arguments: ["%tekstove.api_url%", "@security.token_storage", "@request_stack"]
        public: true
            
    tekstove.gateway.userProvider:
        class: Tekstove\SiteBundle\Model\User\Provider\ApiGateway
        factory: ["@tekstove.gateway.factory", createUserProviderGateway]
        shared: false
        public: true

    tekstove.gateway.user:
        class: Tekstove\SiteBundle\Model\Gateway\User\UserGateway
        factory: ["@tekstove.gateway.factory", createUserGateway]
        shared: false
        public: true

    app.gateway.v4.publisher:
        class: Tekstove\SiteBundle\Model\Gateway\Tekstove\Publisher\PublisherGateway
        factory: ["@tekstove.gateway.factory", createTekstovePublisherGateway]
        shared: false
        public: true
        
    tekstove.gateway.user.pm:
        class: Tekstove\SiteBundle\Model\Gateway\Tekstove\User\PmGateway
        factory: ["@tekstove.gateway.factory", createUserPmGateway]
        shared: false
        public: true
        
    tekstove.gateway.user.register:
        class: Tekstove\SiteBundle\Model\Gateway\User\UserGateway
        factory: ["@tekstove.gateway.factory", createUserRegisterGateway]
        shared: false
        public: true

    tesktove.gateway.lyric:
        class: Tekstove\SiteBundle\Model\Gateway\Lyric\LyricGateway
        factory: ["@tekstove.gateway.factory", createLyricGateway]
        shared: false

    tesktove.gateway.v4.lyric:
        class: Tekstove\SiteBundle\Model\Gateway\Lyric\LyricGateway
        factory: ["@tekstove.gateway.factory", createLyricV4Gateway]
        shared: false
        public: true
        
    tekstove.gateway.lyric.credentials:
        class: Tekstove\SiteBundle\Model\Gateway\Lyric\LyricGateway
        factory: ["@tekstove.gateway.factory", createLyricCredentialsGateway]
        arguments: ["@security.token_storage"]
        shared: false
        public: true
        
    tekstove.gateway.lyric.popularity.history:
        class: Tekstove\SiteBundle\Model\Gateway\Tekstove\Lyric\LyricPopularHistoryGateway
        factory: ["@tekstove.gateway.factory", createLyricPopularityHistoryGateway]
        arguments: ["@security.token_storage"]
        shared: false
        public: true

    tekstove.gateway.artist:
        class: Tekstove\SiteBundle\Model\Gateway\Artist\ArtistGateway
        factory: ["@tekstove.gateway.factory", createArtistGateway]
        shared: false

    tekstove.gateway.v4.artist:
        class: Tekstove\SiteBundle\Model\Gateway\Artist\ArtistGateway
        factory: ["@tekstove.gateway.factory", createArtistV4Gateway]
        shared: false
        public: true
        
    tekstove.gateway.artist.credentials:
        class: Tekstove\SiteBundle\Model\Gateway\Artist\ArtistGateway
        factory: ["@tekstove.gateway.factory", createArtistCredentialsGateway]
        shared: false
        public: true
        
    tekstove.gateway.album:
        class: Tekstove\SiteBundle\Model\Gateway\Album\AlbumGateway
        factory: ["@tekstove.gateway.factory", createAlbumGateway]
        shared: false
        public: true

    tekstove.gateway.album.credentials:
        class: Tekstove\SiteBundle\Model\Gateway\Tekstove\Album\AlbumCredentialsGateway
        factory: ["@tekstove.gateway.factory", createAlbumCredentialsGateway]
        shared: false
        public: true

    tekstove.gateway.forum.category:
        class: Tekstove\SiteBundle\Model\Gateway\Forum\CategoryGateway
        factory: ["@tekstove.gateway.factory", createForumCategoryGateway]
        shared: false
        public: true
        
    tekstove.gateway.forum.topic:
        class: Tekstove\SiteBundle\Model\Gateway\Forum\TopicGateway
        factory: ["@tekstove.gateway.factory", createForumTopicGateway]
        shared: false
        public: true

    tekstove.gateway.forum.post:
        class: Tekstove\SiteBundle\Model\Gateway\Forum\PostGateway
        factory: ["@tekstove.gateway.factory", createForumPostGateway]
        shared: false
        public: true
    
    tekstove.gateway.language:
        class: Tekstove\SiteBundle\Model\Gateway\Tekstove\Language\LanguageGateway
        factory: ["@tekstove.gateway.factory", createLanguageGateway]
        shared: false
        public: true

    wsse.security.authentication.provider:
        class: Tekstove\SiteBundle\Security\Authentication\Provider\TekstoveApiWsseProvider
        arguments:
            - '@tekstove.provider.user'
        public: false

    security.authentication.failure_handler:
        class: Symfony\Component\Security\Http\Authentication\DefaultAuthenticationFailureHandler
        arguments:
            - "@http_kernel"
            - "@security.http_utils"
        public: true

    security.authentication.success_handler:
        class: Symfony\Component\Security\Http\Authentication\DefaultAuthenticationSuccessHandler
        arguments:
            - "@security.http_utils"
        public: true

    wsse.security.authentication.listener:
        class: Tekstove\SiteBundle\Security\Firewall\TekstoveApiWsseListener
        arguments:
          - '@security.token_storage'
          - '@security.authentication.manager'
          - '@security.authentication.session_strategy'
          - '@security.http_utils'
          - 'wsse'
          - '@security.authentication.success_handler'
          - '@security.authentication.failure_handler'
          - []
          - '@logger'
          - ~
        public: false

    tekstove.user.force.terms:
        class: Tekstove\SiteBundle\Event\User\TermsForceListener
        arguments: ['@security.token_storage']
        tags:
            - { name: kernel.event_listener, event: kernel.request }
        public: true

    tekstove.form.lyric:
        class: Tekstove\SiteBundle\Form\Type\LyricType
        arguments: ['@request_stack', '@tekstove.gateway.artist', '@tekstove.gateway.language']
        tags:
            - { name: form.type }
        public: true

    tekstove.form.album:
        class: Tekstove\SiteBundle\Form\Type\Album\AlbumType
        arguments: ['@request_stack', '@tekstove.gateway.artist', '@tekstove.gateway.language']
        tags:
            - { name: form.type }

    tekstove.site.gateway_pagination:
        class: Tekstove\SiteBundle\Subscriber\TekstoveGatewayPaginationSubscriber
        arguments: ['@request_stack']
        tags:
            - { name: knp_paginator.subscriber }
        public: true

    tekstove.site.twig.filter.loggedOnly:
        class: Tekstove\SiteBundle\Twig\Filter\LoggedOnlyLink
        arguments: ["@security.token_storage", "@router"]
        public: false
        tags:
            - { name: twig.extension }

    tekstove.site.twig.extension.text:
        class: Twig_Extensions_Extension_Text
        public: false
        tags:
            - { name: twig.extension }

    tekstove.site.twig.extension.ads_name:
        class: Tekstove\SiteBundle\Twig\Filter\AdsName
        public: false
        arguments: ["@tekstove.site.ads"]
        tags:
            - { name: twig.extension }

    tekstove.site.ads:
        class: Tekstove\SiteBundle\Ads\Ads
        public: true
