twig:
    default_path: '%kernel.project_dir%/templates'
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'
    paths:
        "%kernel.root_dir%/../src/Tekstove/SiteBundle/Resources/views": TekstoveSite
    form_themes:
        - "@TekstoveSite/Form/Type/Artists.html.twig"
        - "bootstrap_3_layout.html.twig"
    globals:
        tekstove_api_url: '%tekstove.api_url%'
