engines:
    csslint:
        enabled: true
    duplication:
        enabled: true
        config:
            languages:
                - php
                - javascript

ratings:
    paths:
        - "src/**"

exclude_paths:
    - "src/Tekstove/SiteBundle/Resources/public/js/blockui-2.70/"
    - "src/Tekstove/SiteBundle/Resources/public/css/smoothness/jquery-ui-1.10.3.custom.css"
