php_version: 7

global_exclude_dirs:
    - vendor
    - Test
    - app/scripts/cron

exclude_patterns:
    - app/config/parameters_travis.yml
    - web/app_dev.php

rules:
    php.class_too_long:
        enabled: true
        max_length: 500
    php.method_too_long:
        enabled: true
        max_length: 100
    symfony.controller.action_method_too_long:
        enabled: true
        max_length: 100
        threshold: 1
    twig.xss_vulnerability:
        # bbcode to html is done in api. We have false-positive xss vulnerabilities.
        enabled: false
