language: php
php:
  - 5.4
  - 5.5
  - 5.6
before_script:
  - composer self-update
  - composer install --prefer-dist

script:
    - app/console doctrine:mapping:info

notifications:
    on_success: always
    on_failure: always
