language: php
php:
  - 7.1
  - 7.2
  - nightly


before_script:
  - phpenv rehash

script:
    - composer install -d Test/codeSniffer/ --prefer-dist --no-dev
    - Test/codeSniffer/vendor/bin/phpcs --standard=Test/codeSniffer/phpcs.xml src/
    - composer install --prefer-dist
    - vendor/bin/phpunit -c Test/phpUnit/phpunit.xml --no-coverage

matrix:
    allow_failures:
        - php: nightly

notifications:
    on_success: never
    on_failure: never
    on_change: never
