language: php
php:
  - 5.4
  - 5.5
  - 5.6
before_script:
  - mv app/config/parameters_travis.yml app/config/parameters.yml
  - mysql -e 'create database tekstove_lyric;'
  - composer self-update
  - composer install

script:
    - app/console doctrine:mapping:info

notifications:
    on_success: never
    on_failure: always
