index:
    path:     /
    defaults: { _controller: TekstoveBundle:Index:index }
contactsFriends:
    path: /contacts/partners
    defaults: { _controller: TekstoveBundle:Contacts:partners }
contacts:
    path: /contacts
    defaults: { _controller: TekstoveBundle:Contacts:contacts }
login:
    path: /user/login
    defaults: { _controller: TekstoveBundle:User:login }
loginCheck:
    path: /user/loginCheck
logout:
    path: /user/logout
register:
    path: /user/register
    defaults: { _controller: TekstoveBundle:User:register }
userView:
    path: /user/view/{id}
    defaults: { _controller: TekstoveBundle:User:view }
    
lyricView:
    path: /lyric/view/{id}
    defaults: { _controller: TekstoveBundle:Lyric:view }
    requirements:
        id:  \d+

lyricAddPostHtml:
    path: /lyric/add
    defaults: { _controller: TekstoveBundle:Lyric:addHtml }
    methods: [POST]

lyricAdd:
    path: /lyric/add
    defaults: { _controller: TekstoveBundle:Lyric:add }
    methods: [GET]
lyricEdit:
    path: /lyric/edit/{id}
    defaults: { _controller: TekstoveBundle:Lyric:edit }
    requirements:
        id: \d+

artistBrowse:
    path: /artist/browse/{id}
    defaults: { _controller: TekstoveBundle:Artist:browse }
    requirements:
        id: \d+
artistList:
    path: /artist/list/{letter}
    defaults: { _controller: TekstoveBundle:Artist:list }
