security:
    encoders:
        Tekstove\TekstoveBundle\Entity\User:
            class: Tekstove\TekstoveBundle\Entity\User
            algorithm: md5
            encode_as_base64: false
            iterations: 1
    providers:
        localDb:
            entity:
                class: Tekstove\TekstoveBundle\Entity\User
                property: username
    firewalls:
        secured_area:
            pattern:   ^/
            anonymous: ~
            form_login:
                login_path: login
                check_path: loginCheck
            logout:
                path:   logout
                target: /
