parameters:
    tekstoveBundleUserProvider.class: Tekstove\TekstoveBundle\Model\User\Provider
    tekstoveBundleUserManager.class: Tekstove\TekstoveBundle\Model\User\Manager
    
services:
    tekstoveCache.cache.memcached:
        class: Tekstove\CacheBundle\Model\Cache\Adapter\Memcached
        arguments:
            - { host: 'localhost', port: 11211, weight: ~ }
    tekstoveCache.cache:
        class: Tekstove\CacheBundle\Model\Cache
        arguments: [@tekstoveCache.cache.memcached]
    
    
    tekstove.model.user.query:
        class:   Tekstove\TekstoveBundle\Model\UserQuery
    
    tekstove.event_dispacher.factory:
        class: Tekstove\TekstoveBundle\EventDispatcher\EventDispacherFactory
        arguments: []
    
    tekstove.event_dispacher:
        class: Tekstove\TekstoveBundle\EventDispatcher\EventDispacher
        factory: [@tekstove.event_dispacher.factory, createDispacher]
        arguments: [@service_container]
    
    tekstove.lyric.repository:
        class: Tekstove\TekstoveBundle\Model\LyricRepository
        arguments: [@tekstove.event_dispacher, @tekstoveCache.cache]
    
    tekstove.security.lyric_voter:
        class: Tekstove\TekstoveBundle\Security\Authorization\Voter\LyricVoter
        public: false
        tags:
            - { name: security.voter }
    
    tekstove.provider.user:
        class: Tekstove\TekstoveBundle\Model\User\Provider
        arguments: [@tekstove.model.user.query]
