parameters:
    tekstoveBundleUserProvider.class: Tekstove\TekstoveBundle\Model\User\Provider
    tekstoveBundleUserManager.class: Tekstove\TekstoveBundle\Model\User\Manager
    
services:
    tekstove.model.user.query:
        class:   Tekstove\TekstoveBundle\Model\UserQuery
    
    tekstove.event_dispacher.factory:
        class: Tekstove\TekstoveBundle\Model\EventDispatcher\EventDispacherFactory
        arguments: []
    tekstove.event_dispacher:
        class: Tekstove\TekstoveBundle\Model\EventDispatcher\EventDispacher
        factory: [@tekstove.event_dispacher.factory, createDispacher]
        arguments: [@service_container]
    
    security.access.post_voter:
        class: Tekstove\TekstoveBundle\Model\Security\Authorization\Voter\LyricVoter
        public: false
        tags:
            - { name: security.voter }
    tekstove.provider.user:
        class: Tekstove\TekstoveBundle\Model\User\Provider
        arguments: [@tekstove.model.user.query]
