parameters:
    tekstoveBundleUserProvider.class: Tekstove\TekstoveBundle\Model\User\Provider
    tekstoveBundleUserManager.class: Tekstove\TekstoveBundle\Model\User\Manager
    
services:
    security.access.post_voter:
        class: Tekstove\TekstoveBundle\Model\Security\Authorization\Voter\LyricVoter
        public: false
        tags:
            - { name: security.voter }
