services:
    tekstoveCache.cache.memcached:
        class: Tekstove\CacheBundle\Model\Cache\Adapter\Memcached
        arguments:
            server1:
                - { host: 'localhost', port: 11211, weight: ~ }
    tekstoveCache.cache:
        class: Tekstove\CacheBundle\Model\Cache
        arguments: [@tekstoveCache.cache.memcached]
    
    
    tekstove.event_dispacher.factory:
        class: Tekstove\TekstoveBundle\EventDispatcher\EventDispacherFactory
        arguments: []
    
    tekstove.event_dispacher:
        class: Tekstove\TekstoveBundle\EventDispatcher\EventDispacher
        factory: [@tekstove.event_dispacher.factory, createDispacher]
        arguments: [@service_container]
    
    tekstove.security.lyric_voter:
        class: Tekstove\TekstoveBundle\Security\Authorization\Voter\LyricVoter
        public: false
        tags:
            - { name: security.voter }
    
    tekstove.provider.user:
        class: Tekstove\TekstoveBundle\Model\User\Provider

    tesktove.gateway.lyric:
        class: Tekstove\TekstoveBundle\Model\Gateway\Lyric\LyricGateway
        factory: [Tekstove\TekstoveBundle\Model\Gateway\GatewayFactory, createLyricGateway]
