version: '2'

services:
  tekstove.site-web:
    image: tekstoveinfo/site.web:latest
    volumes:
      - ../:/var/www/tekstove-site
    external_links:
        - docker_tekstove.api-web_1
    restart: always
