# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: 'en'
    tekstove.api_url: '%env(APP_API_URL)%/'

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.
        public: false       # Allows optimizing the container by removing unused services; this also means
                            # fetching services directly from the container via $container->get() won't work.
                            # The best practice is to be explicit about your dependencies anyway.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/*'
        exclude: '../src/{DependencyInjection,Entity,Migrations,Tests,Kernel.php,Tekstove}'

    # controllers are imported separately to make sure services can be injected
    # as action arguments even if you don't extend any base controller class
    App\Controller\:
        resource: '../src/Controller'
        tags: ['controller.service_arguments']

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones


    tekstove.provider.user:
        class: Tekstove\SiteBundle\Model\User\Provider\ApiProvider
        arguments: ["@tekstove.gateway.userProvider"]
        public: true

    tekstove.gateway.factory:
        class: Tekstove\SiteBundle\Model\Gateway\GatewayFactory
        arguments: ["%tekstove.api_url%", "@security.token_storage", "@request_stack"]
        public: true

    tekstove.gateway.userProvider:
        class: Tekstove\SiteBundle\Model\User\Provider\ApiGateway
        factory: ["@tekstove.gateway.factory", createUserProviderGateway]
        shared: false
        public: true

    tekstove.gateway.user:
        class: Tekstove\SiteBundle\Model\Gateway\User\UserGateway
        factory: ["@tekstove.gateway.factory", createUserGateway]
        shared: false
        public: true

    App\Gateway\Tekstove\V4\Publisher\PublisherGateway:
        factory: ["@tekstove.gateway.factory", createTekstovePublisherGateway]
        shared: false

    tekstove.gateway.user.pm:
        class: Tekstove\SiteBundle\Model\Gateway\Tekstove\User\PmGateway
        factory: ["@tekstove.gateway.factory", createUserPmGateway]
        shared: false
        public: true

    Tekstove\SiteBundle\Model\Gateway\Tekstove\User\PmGateway: '@tekstove.gateway.user.pm'

    tekstove.gateway.user.register:
        class: Tekstove\SiteBundle\Model\Gateway\User\UserGateway
        factory: ["@tekstove.gateway.factory", createUserRegisterGateway]
        shared: false
        public: true

    tesktove.gateway.lyric:
        class: Tekstove\SiteBundle\Model\Gateway\Tekstove\Lyric\LyricGateway
        factory: ["@tekstove.gateway.factory", createLyricGateway]
        shared: false
        public: true

    Tekstove\SiteBundle\Model\Gateway\Tekstove\Lyric\LyricGateway: '@tesktove.gateway.lyric'

    tesktove.gateway.v4.lyric:
        class: Tekstove\SiteBundle\Model\Gateway\Lyric\LyricGateway
        factory: ["@tekstove.gateway.factory", createLyricV4Gateway]
        shared: false
        public: true

    App\Gateway\Tekstove\Lyric\LyricGatewayV4:
        factory: ["@tekstove.gateway.factory", createLyricV4Gateway]
        shared: false

    App\Gateway\Tekstove\V4\Lyric\LyricGateway: '@App\Gateway\Tekstove\Lyric\LyricGatewayV4'

    tekstove.gateway.lyric.credentials:
        class: Tekstove\SiteBundle\Model\Gateway\Lyric\LyricGateway
        factory: ["@tekstove.gateway.factory", createLyricCredentialsGateway]
        arguments: ["@security.token_storage"]
        shared: false
        public: true

    tekstove.gateway.lyric.popularity.history:
        class: Tekstove\SiteBundle\Model\Gateway\Tekstove\Lyric\LyricPopularHistoryGateway
        factory: ["@tekstove.gateway.factory", createLyricPopularityHistoryGateway]
        arguments: ["@security.token_storage"]
        shared: false
        public: true

    tekstove.gateway.artist:
        class: Tekstove\SiteBundle\Model\Gateway\Artist\ArtistGateway
        factory: ["@tekstove.gateway.factory", createArtistGateway]
        shared: false
        public: true

    tekstove.gateway.v4.artist:
        class: Tekstove\SiteBundle\Model\Gateway\Artist\ArtistGateway
        factory: ["@tekstove.gateway.factory", createArtistV4Gateway]
        shared: false
        public: true

    tekstove.gateway.artist.credentials:
        class: Tekstove\SiteBundle\Model\Gateway\Artist\ArtistGateway
        factory: ["@tekstove.gateway.factory", createArtistCredentialsGateway]
        shared: false
        public: true

    tekstove.gateway.forum.category:
        class: Tekstove\SiteBundle\Model\Gateway\Forum\CategoryGateway
        factory: ["@tekstove.gateway.factory", createForumCategoryGateway]
        shared: false
        public: true

    tekstove.gateway.forum.topic:
        class: Tekstove\SiteBundle\Model\Gateway\Forum\TopicGateway
        factory: ["@tekstove.gateway.factory", createForumTopicGateway]
        shared: false
        public: true

    tekstove.gateway.forum.post:
        class: Tekstove\SiteBundle\Model\Gateway\Forum\PostGateway
        factory: ["@tekstove.gateway.factory", createForumPostGateway]
        shared: false
        public: true

    tekstove.gateway.language:
        class: Tekstove\SiteBundle\Model\Gateway\Tekstove\Language\LanguageGateway
        factory: ["@tekstove.gateway.factory", createLanguageGateway]
        shared: false
        public: true

    wsse.security.authentication.provider:
        class: Tekstove\SiteBundle\Security\Authentication\Provider\TekstoveApiWsseProvider
        arguments:
            - '@tekstove.provider.user'
        public: false

    security.authentication.failure_handler:
        class: Symfony\Component\Security\Http\Authentication\DefaultAuthenticationFailureHandler
        arguments:
            - "@http_kernel"
            - "@security.http_utils"
        public: true

    security.authentication.success_handler:
        class: Symfony\Component\Security\Http\Authentication\DefaultAuthenticationSuccessHandler
        arguments:
            - "@security.http_utils"
        public: true

    wsse.security.authentication.listener:
        class: Tekstove\SiteBundle\Security\Firewall\TekstoveApiWsseListener
        arguments:
            - '@security.token_storage'
            - '@security.authentication.manager'
            - '@security.authentication.session_strategy'
            - '@security.http_utils'
            - 'wsse'
            - '@security.authentication.success_handler'
            - '@security.authentication.failure_handler'
            - { require_previous_session: false }
            - '@logger'
            - ~
        public: false

    tekstove.user.force.terms:
        class: Tekstove\SiteBundle\Event\User\TermsForceListener
        arguments: ['@security.token_storage']
        tags:
            - { name: kernel.event_listener, event: kernel.request }
        public: true

    tekstove.form.lyric:
        class: Tekstove\SiteBundle\Form\Type\LyricType
        arguments: ['@request_stack', '@tekstove.gateway.artist', '@tekstove.gateway.language']
        tags:
            - { name: form.type }
        public: true

    tekstove.site.gateway_pagination:
        class: App\Subscriber\TekstoveGatewayPaginationSubscriber
        arguments: ['@request_stack']
        tags:
            - { name: knp_paginator.subscriber }
        public: true

    tekstove.site.twig.extension.text:
        class: Twig_Extensions_Extension_Text
        public: false
        tags:
            - { name: twig.extension }
